import { describe, it, expect } from "vitest";
import { sha256Hex, verifyHmac, verifyEd25519, bytesToHex, hexToBytes, decodeBase64 } from "../src/crypto";

const PUB = "d04ab232742bb4ab3a1368bd4615e4e6d0224ab71a016baf8520a332c9778737";
const SHA = "bbf6124fd0287f049f9bd572995c6d04874b173eeeb32b070aef2504d686b87f";
const SIG = "c65488d6b784562fbcf30cc542f3dbbe139189b8e9d3ed5a969665f85a6ffbcc576115294df8c7bd46da02bd2a40e1bbae305cd1d01a22c2c9865f42395ecf01";
const BODY = '{"counter": 1, "ts": 1, "sha256": "bbf6124fd0287f049f9bd572995c6d04874b173eeeb32b070aef2504d686b87f", "sig": "c65488d6b784562fbcf30cc542f3dbbe139189b8e9d3ed5a969665f85a6ffbcc576115294df8c7bd46da02bd2a40e1bbae305cd1d01a22c2c9865f42395ecf01", "croText": null, "image_b64": "anBlZ2J5dGVz"}';
const MAC = "b75cfa9914178e90e880548eb771ac7b135f7a8c76f90439c91df519dcefc230";
const enc = new TextEncoder();

describe("crypto vectors (authoritative, generated by beadz_camera)", () => {
  it("sha256Hex matches Python hexdigest, lowercase", async () => {
    expect(await sha256Hex(enc.encode("jpegbytes"))).toBe(SHA);
  });
  it("verifyHmac accepts the real MAC over the real body", async () => {
    expect(await verifyHmac("test-secret", enc.encode(BODY), MAC)).toBe(true);
  });
  it("verifyHmac rejects a wrong MAC", async () => {
    expect(await verifyHmac("test-secret", enc.encode(BODY), "0".repeat(64))).toBe(false);
  });
  it("verifyHmac returns false (not throws) on malformed hex", async () => {
    expect(await verifyHmac("test-secret", enc.encode(BODY), "zz")).toBe(false);
  });
  it("verifyEd25519 verifies the real signature over the 32 digest bytes", async () => {
    expect(await verifyEd25519(PUB, SHA, SIG)).toBe(true);
  });
  it("verifyEd25519 rejects a tampered digest", async () => {
    expect(await verifyEd25519(PUB, "ab".repeat(32), SIG)).toBe(false);
  });
  it("verifyEd25519 returns false (not throws) on malformed hex", async () => {
    expect(await verifyEd25519(PUB, "not-hex", SIG)).toBe(false);
  });
  it("hex round-trips lowercase", () => {
    expect(bytesToHex(hexToBytes("00 FF".replace(" ", "")))).toBe("00ff");
  });
  it("decodeBase64 throws on invalid input", () => {
    expect(() => decodeBase64("@@@not base64@@@")).toThrow();
  });
});
